baseurl = "/"
title = "Digital Research Alliance of Canada - HSS Winter Series 2023"

languagecode = "en"
defaultcontentlanguage = "en"

buildFuture = true
footnotereturnlinkcontents = "↩"
relativeURLs = true

enableEmoji = true

paginate = 20
canonifyurls = true

# pygmentsstyle = "b2"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"

[params]
  author = "Digital Research Alliance of Canada | Alliance de recherche numérique du Canada"
  description = ""
  keywords = ""
  info = "Winter 2023 | Hiver 2023"
  wgavatar = "/images/drac.svg"
  favicon_32 = "/images/favicon.png"
  error = "/img/404.png"
  dateformat = "January 2, 2006"
  hideCredits = false
  hideCopyright = false
  since = 2023
  rtl = false
  math = true

  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorscheme = "light"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
  siteID = "ABCDE"
  # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
  serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
  [languages.en]
    languagename = "English"

    [languages.en.menu]

      # [[languages.en.menu.main]]
      # name = "Intro"
      # weight = 1
      # url = "bash-menu"

      # [[languages.en.menu.main]]
      # name = "Cloud"
      # weight = 2
      # url = "git"

      # [[languages.en.menu.main]]
      # name = "DMPs"
      # weight = 3
      # url = "hpc-menu"

      # [[languages.en.menu.main]]
      # name = "ProjectManagement"
      # weight = 4
      # url = "python-menu"

	  # [[languages.en.menu.main]]
	  # name = "Tools"
	  # weight = 5
	  # url  = "pytorch"

	  # [[languages.en.menu.main]]
	  # name = "CLI"
	  # weight = 6
	  # url  = "chapel-menu"

	  # [[languages.en.menu.main]]
	  # name = "Photogrammetry"
	  # weight = 7
	  # url  = "julia"

	  # [[languages.en.menu.main]]
	  # name = "WebScraping"
	  # weight = 8
	  # url  = "vis-menu"
