---
title: Moissonnage du Web avec R
slug: webscrapingfr
execute:
  error: true
format: hugo-md
---

**16 février 2023, 13h30 à 14h50 HNE**

**Présenté par**: Pier-Luc St-Onge

**Durée**: 80 minutes

**Description**: Internet est non seulement un trésor riche en informations, mais une grande portion y est
accessible publiquement, ce qui est propice à une utilisation pour la recherche. Cependant, extraire
l’information de pages Web et la formater pour analyse peut rapidement devenir une tâche fastidieuse. Les
outils de moissonnage du Web permettent d’automatiser en partie ce processus et le langage R est populaire
pour réaliser cette tâche. Dans cet atelier, nous allons donc vous guider à travers un exemple simple
utilisant le module rvest.

Inscrivez-vous [ici](https://www.eventbrite.ca/e/512943125697){target="_blank"}

The same workshop [in English](/webscraping).

#### Biographie

Diplômé au baccalauréat et à la maîtrise en génie logiciel et génie informatique, **Pier-Luc St-Onge** a
travaillé pendant cinq ans pour différents laboratoires de recherche avant de rejoindre Calcul Québec en
mai 2013. Dans son projet de recherche, il s’était spécialisé en vision par ordinateur avec OpenCV. À Calcul
Québec, il fait partie de l’équipe d’analystes offrant du soutien aux utilisateurs des ressources de calcul.

<!-- {{< vimeo 690948795 >}} -->
<!-- <br> -->

<!-- - [Watch this session on Vimeo](https://vimeo.com/690948795) -->
